<style type="text/css">

.linkA
{
    COLOR: #000000;
    FONT-FAMILY: verdana;
    FONT-SIZE: 11px;
    TEXT-DECORATION: none
}

.linkB
{
    COLOR: #000099;
    FONT-FAMILY: verdana;
    FONT-SIZE: 11px;
    TEXT-DECORATION: none
}
A.linkB:visited
{
    COLOR: #000099; 
    FONT-FAMILY: verdana; 
    FONT-SIZE: 11px; 
    TEXT-DECORATION: none
}
A.linkB:link
{
    COLOR: #000099; 
    FONT-FAMILY: verdana; 
    FONT-SIZE: 11px; 
    TEXT-DECORATION: none
}
A.linkB:hover
{
    COLOR: #CC0000; 
    FONT-FAMILY: verdana; 
    FONT-SIZE: 11px; 
    TEXT-DECORATION: NONE
}



.linkC
{
    COLOR: #666666;
    FONT-FAMILY: verdana;
    FONT-SIZE: 11px;
    TEXT-DECORATION: none
}
A.linkC:visited
{
    COLOR: #666666; 
    FONT-FAMILY: verdana; 
    FONT-SIZE: 11px; 
    TEXT-DECORATION: none
}
A.linkC:link
{
    COLOR: #666666; 
    FONT-FAMILY: verdana; 
    FONT-SIZE: 11px; 
    TEXT-DECORATION: none
}
A.linkC:hover
{
    COLOR: #000000; 
    FONT-FAMILY: verdana; 
    FONT-SIZE: 11px; 
    TEXT-DECORATION: none
}

</style>
